#!/bin/sh
AWK=awk
$AWK -F';' '
  {
    if(!num[$1] || $2>max[$1]) max[$1]=$2
    if(!num[$1] || $2<min[$1]) min[$1]=$2
    total[$1]+=$2
    num[$1]++
  }
  END {
    for(x in total) printf("%s=%.1f/%.1f/%.1f\n", x, min[x], total[x]/num[x], max[x])
  }
' $1 | sort | $AWK '
  {
    if(!NR)
      printf("{%s", $0)
    else
      printf(", %s", $0)
  }
  END { if(NR) printf "}\n" }
'
